export const Photos = {
    LOADING_PHOTOS: 'PHOTOS/LOADING_PHOTOS',
    SET_PHOTOS: 'PHOTOS/SET_PHOTOS',
    ADD_LOCALE_PHOTO: 'PHOTOS/ADD_LOCALE_PHOTO'
}

export const Albums = {
    LOADING_ALBUMS: 'ALBUMS/LOADING_ALBUMS',
    SET_ACTIVE_ALBUM: 'ALBUM/SET_ACTIVE_ALBUM',
    ADD_LOCALE_ALBUM: 'ALBUMS/ADD_LOCALE_ALBUM'
}